version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ai-assistant-app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app/app:ro  # Read-only for security
      - ./data:/usr/src/app/data   # Persistent data
      - ./logs:/usr/src/app/logs   # Application logs
    environment:
      - FLASK_APP=app/main.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
      - PYTHONPATH=/usr/src/app
    env_file:
      - .env
    networks:
      - assistant_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  n8n:
    image: n8nio/n8n:latest
    container_name: ai-assistant-n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./n8n_workflows:/home/node/workflows:ro
    networks:
      - assistant_network
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_USER_MANAGEMENT_DISABLED=true
      - NODE_ENV=development
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=UTC
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  # Optional: Add a simple web interface
  nginx:
    image: nginx:alpine
    container_name: ai-assistant-nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/html/static:ro
    depends_on:
      - app
    networks:
      - assistant_network
    restart: unless-stopped
    profiles:
      - with-nginx

networks:
  assistant_network:
    driver: bridge
    name: ai-assistant-network

volumes:
  n8n_data:
    name: ai-assistant-n8n-data
  app_data:
    name: ai-assistant-app-data